### PR TITLE
Adding nmaps -oA option to interessting hosts scan

### PR DESCRIPTION
**Pull request by randomisresistance**
Adding the -oA option of nmap to export results in useful formats and upload them to the C2 Cloud. For further use in a pentest.

### CODE REVIEW

**Comment by foxtrot** [comment]
Hi @randomisresistance

Thanks for the PR. Can you confirm that you've runtime tested this on the Shark?

**Comment by randomisresistance** [comment]
Hi foxtrot, 
I have tested it on my SharkJack several times. Files are generated and uploaded to the C2 instance with correct naming/numbering. But after thinking more about it this should also be added to the normal scan option. Since INTERESTING_HOSTS_PATTERN="Synology|QNAP"

**Comment by foxtrot** [comment]
Great. I'm happy to merge this if you don't have any other pending changes.

**Comment by randomisresistance** [comment]
Just the other one from the pull request. Sorry could not merg it in one pull for some reason.

**Comment by foxtrot** [comment]
All good!

**Pull request merged**
